### ISSUE TITLE
dependabotをとりあえずの最小導入

### ISSUE THREAD

**Issue by masal9pse** [masal9pse/flutter_search_repository_app#176]
.github/dependabot.ymlに以下を指定する

```yaml
version: 2
updates:
  - package-ecosystem: "pub"   # Dart/Flutterのパッケージ管理システム
    directory: "/"              # プロジェクトのルートディレクトリ、直接pubspec.yamlは指定できない
    schedule:
      interval: "weekly"        # 週に1回更新をチェック

```

参考サイト

https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference#about-the-dependabotyml-file => 公式
https://qiita.com/yokawasa/items/38c6a4242cbe0fd5bbf0
https://zenn.dev/imajoriri/articles/c25b40bec11fa6#dependabot
