### ISSUE TITLE
リリースノート作成の際にmasterにマージされる以外のやり方ではエラーになる

### ISSUE THREAD

**Issue by masal9pse** [masal9pse/flutter_search_repository_app#188]
### summary
例えばfeatureブランチのpushでリリースノートを作成しようとしたら以下のエラー

```bash
Warning: masal9pse/flutter_search_repository_app: Invalid config file
{
  name: 'event',
  id: '[12](https://github.com/masal9pse/flutter_search_repository_app/actions/runs/12535203175/job/34956838932#step:2:13)535203175',
  stack: 'Error: Configuration file .github/release-drafter.yml is not found. The configuration file must reside in your default branch.\n' +
    '    at getConfig (/home/runner/work/_actions/release-drafter/release-drafter/v6/dist/index.js:142745:[13](https://github.com/masal9pse/flutter_search_repository_app/actions/runs/12535203175/job/34956838932#step:2:14))\n' +
    '    at async /home/runner/work/_actions/release-drafter/release-drafter/v6/dist/index.js:[14](https://github.com/masal9pse/flutter_search_repository_app/actions/runs/12535203175/job/34956838932#step:2:15)2240:22\n' +
    '    at async Promise.all (index 0)',
  type: 'Error'
}
Error: Invalid config file
Warning: masal9pse/flutter_search_repository_app: Invalid config file
{
  name: 'event',
  id: '12535203175',
  stack: 'Error: Configuration file .github/release-drafter.yml is not found. The configuration file must reside in your default branch.\n' +
    '    at getConfig (/home/runner/work/_actions/release-drafter/release-drafter/v6/dist/index.js:142745:13)\n' +
    '    at async drafter (/home/runner/work/_actions/release-drafter/release-drafter/v6/dist/index.js:142339:[20](https://github.com/masal9pse/flutter_search_repository_app/actions/runs/12535203175/job/34956838932#step:2:21))\n' +
    '    at async Promise.all (index 1)',
  type: 'Error'
}
Error: Invalid config file
```

### reference

**Comment by masal9pse** [comment]
commitishに作りたいリリースノートのブランチを入れると出来た。
全てのブランチの際に*を指定するとエラーになるが、目的はmasterにマージする前に動作確認することなので一旦クローズとする

```yml
name: Release Drafter

on:
  # push:
    # branches to consider in the event; optional, defaults to all
    # branches:
    #   - master
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          commitish: feature/why-success-releasenote　// これ
        #   config-name: my-config.yml
        #   disable-autolabeler: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
